#!/bin/sh

if [ ! -f composer.phar ]
then
	echo "Composer not installed installing composer from getcomposer.org...\n"

	curl http://getcomposer.org/download/2.3.5/composer.phar --output composer.phar

	echo "Done installing composer.\n"
fi

php composer.phar $@
